# Matrix
23 feb 2022 linear algebra

oprasi matematika matriks, konvers invers determinan tensorflow
- bisa mengerti matrix
- melakukan oprasi metrik
- kenalan sm tensor
- implementasi matrik pada python

MATRIK 2D array

jumlah baris, jumlah kolom
a=np.array([[1,2],[2,3],[4,5]])
ada 3 barus 2 kolom

In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [3]:
matrix = np.array([[1,2],
                  [3,4],
                  [5,6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
matrix.shape

(3, 2)

## cara akses komponen atau element dalam matrix

In [5]:
A = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
A[0]

array([1, 2, 3])

In [8]:
A[1]

array([4, 5, 6])

In [9]:
A[2]

array([7, 8, 9])

kalo kita mau akses secara spesifik ada 2 cara
baris dulu baru indexing kolom , misal kita mau ambil angka 6

In [10]:
A[1][2]

6

In [11]:
A[1,2]

6

In [12]:
#tampilkan all kolom tapi baris terakhir

A[:,-1]

array([3, 6, 9])

ada beberapa matriks khusus
1. matrik persegi jika semua sisi ada isinya 3x3 ada isi
2. upper triangle
3. lower triangle
4. diagonal
5. identity *special pake telor

--------------------------------------------------------------------------------------------------------------------

angka sepsial

## x + 0 = x
## x * 1 = x

matrix dot matrik identitas = matrik

dengan matrik identitas bisa mencari invers
## invers adalah nilai kebalikan
 suatu bilangan di lakukan oprasi dengan invers nya akan menjadi bilangan identidas

 ## x + inversnya = 0
 8 + (-8) = 0

 ## x * inversnya = 1
 5 * 1/5 = 1
 atau 5 pangkat min 1
 8 * 1/8 = 1

 ----------------------------------------------------------------------------------------------------

 jika matriks di kalikan dengan matriks inversnya maka akan menjadi matrik identitas
 M @ 1/M = MI

## 4. diagonal matrik

In [13]:
np.diag(A)
#4 diagonal matrik

array([1, 5, 9])

In [14]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

## 5. matrik identity

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## ** Operasi Aritmatika **
- penjumlahan
- pengurangan
- pembagian
- perkalian (agak spesial)

**penjumlahan dan pengurangan**

jumlah matrik nya harus sama jadi harus element wise sesuai posisinya

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
B = np.array([[1,8,2],
              [2,1,1],
              [4,0,1]])
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [18]:
A+B

array([[ 2, 10,  5],
       [ 6,  6,  7],
       [11,  8, 10]])

In [19]:
A-B

array([[ 0, -6,  1],
       [ 2,  4,  5],
       [ 3,  8,  8]])

jika melakukan oprasi yang shape nya tidak sama bagaimana? 

In [20]:
z = np.array([[1,8,2],
              [2,1],
              [4,0,1]])
z

array([list([1, 8, 2]), list([2, 1]), list([4, 0, 1])], dtype=object)

In [21]:
A+z

TypeError: unsupported operand type(s) for +: 'int' and 'list'

**pembagian**
dia element wise juga
**sesuai posisi*

In [24]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [22]:
A/B

C:\Users\acer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[1.  , 0.25, 1.5 ],
       [2.  , 5.  , 6.  ],
       [1.75,  inf, 9.  ]])

In [23]:
B/A

array([[1.        , 4.        , 0.66666667],
       [0.5       , 0.2       , 0.16666667],
       [0.57142857, 0.        , 0.11111111]])

**perkalian matrik**
- matrik * skalar
- matrik * hadamar product (yang menggunakan * atau element wise)
- matrix * matrik (yang menggunakan simbol @ mirip dot product tp ada arutan yg harus di penuhi)



In [27]:
#matrik skalar, setiap element akan di kali dengan angka skalarnya
A*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
#perkalian hadamart product, secara umum sama dengan vektor ke vekror, simbol notasinya adalah lingkaran

A*B

array([[ 1, 16,  6],
       [ 8,  5,  6],
       [28,  0,  9]])

### matrik to matrik multiplication yang notasinya @, ada aturan
agak beda dengan perkalian dan aada rule yg harus diikuti

- jomlah kolom di matrik A harus sama dengan baris di matrrik B
- jika di penuhi akan manjadi matrix C
- dimana baris matrik B dan kolom matrik A

misal A(3,2) B(2,2)   
          2 di a sama dengan 2 di awal yg b

    maka akan jadi
    C(3,2) 2 disini yg belakang


# di matriks a * b tidak sama dengan b * a

B(2,2) * A (3,2) tidak bisa karena
b yg ujung 2 dan A yg awal 3
jadi gabisa


sekarang kita tinjau cara perkalianya agar bisa terpenuhi

C(m,n)= A(m,k).B(k,n)



In [29]:
# matrik to matrik multiplication yang notasinya @, ada aturan shape yang terpenuhi 
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [32]:
A*B

array([[ 1, 16,  6],
       [ 8,  5,  6],
       [28,  0,  9]])

In [31]:
A@B 
# ini yang rule tadi jadilah dia matrik baru yang blend

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [33]:
np.dot(A,B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [34]:
A.dot(B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [37]:
C= np.array([[2],
            [1],
            [5]])
C

array([[2],
       [1],
       [5]])

In [38]:
C.shape

(3, 1)

In [41]:
A@C

array([[19],
       [43],
       [67]])

bentuknya berubah matrik multipicationya

In [42]:
C@A
#gabisa karena aturanya tidak terpenuhi

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

## **Transpose**
merubah kolom jadi baris

In [43]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## **Invers**
nilai kebalikan atau 
A inversnya 1/A
shape di atas 3x3 uda ribet sekalikatanya sio gitu

tidak semua matriks ada inverse

ada istilah a jason matrix

jika nilai determinan = 0 maka tidk ada inversnya
karena 
1/0 tidak bisa di oprasikan

## **Determinan**

ada di matriks square
- untu mencari tau apakah matriks ada inversnya atau tidak

misa matriksnya berukuran A(2x2) ([[a,b],[c,d]])
hasilnya adalah skalar  |A| = ad - bc hasilnya adalah skalar

ini untuk melihat suatu matriks ada invers atau tidak

In [56]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

cara manuaaaalll

In [48]:
D = np.array([[1,2],
              [3,4]])

D_adjecent = np.array([[4,-3],
                     [-3,1]])

In [50]:
inv_D = 1/np.linalg.det(D) * D_adjecent
inv_D

array([[-2. ,  1.5],
       [ 1.5, -0.5]])

cara langsung saja pake rumus

In [51]:
np.linalg.inv(D)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [52]:
np.linalg.inv(B)

array([[ 0.11111111, -0.88888889,  0.66666667],
       [ 0.22222222, -0.77777778,  0.33333333],
       [-0.44444444,  3.55555556, -1.66666667]])

In [57]:
np.linalg.inv(A)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [58]:
np.linalg.det(A)

6.66133814775094e-16

Syarat determinan

1. barisnya adalah kelipatan dari baris yang lain
2. kombinasi linier dari baris yang ada

In [59]:
E = np.array([  [1,2,3],
                [2,4,6],
                [1,0,1]])
E

array([[1, 2, 3],
       [2, 4, 6],
       [1, 0, 1]])

In [61]:
np.linalg.inv(E)

#ketika syarat tidak terpenuhi

LinAlgError: Singular matrix

# **TENSOR**
multi dimensional array 
vektor = 1D array
matrik = 2D array
N_dimensional array jika 3D++


secara skala nyebut mereka semua adalah tensor

ada tipe data tensor yg di buka pakai tensor overflow di deep learning nantinya



vektor ->list
matriks -> vektor di dalam list
tensor -> matriks di dalam list

-----------------------------------------------------

cara pembuatan tensor

In [62]:
X = np.array([[1,4,5,6],
                [4,3,7,1]])

print(X)
print('')
print('shape:', X.shape)

[[1 4 5 6]
 [4 3 7 1]]

shape: (2, 4)


In [63]:
Y = np.array([[2,8,8,1],
                [3,0,9,1]])

print(Y)
print('')
print('shape:', Y.shape)

[[2 8 8 1]
 [3 0 9 1]]

shape: (2, 4)


In [64]:
Z = np.array([[2,4,1,1],
                [0,9,4,2]])

print(Z)
print('')
print('shape:', Z.shape)

[[2 4 1 1]
 [0 9 4 2]]

shape: (2, 4)


In [65]:
ListOfMatrix = [X,Y,Z]
tensor = np.array(ListOfMatrix)
tensor

array([[[1, 4, 5, 6],
        [4, 3, 7, 1]],

       [[2, 8, 8, 1],
        [3, 0, 9, 1]],

       [[2, 4, 1, 1],
        [0, 9, 4, 2]]])

liat list pembukanya ada 3 berarti 3 dimensi

In [66]:
tensor.shape

(3, 2, 4)

(3, 2, 4)
melambangkan
3 matrik
2 baris
4 kolom