# Non Graded Challenge 4


 `Name               : Reyki Seprianza`
 `Batch              : FTDS009`

Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Linear Algebra.

-----------------------------------------

1. Buatlah Tensor dibawah ini dengan Python:

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \ 99 & 43 \end{bmatrix} \ \begin{bmatrix} 75 & 21 \ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \ 18 & 84 \end{bmatrix} \end{bmatrix} $$

2. Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} $$

# 1. Membuat tensor

In [2]:
import numpy as np

In [12]:
w = np.array([[23, 50], [7, 12]])
print(w)
print('')
print('shape:', w.shape)

[[23 50]
 [ 7 12]]

shape: (2, 2)


In [13]:
x = np.array([[57,67],[99,43]])
print(x)
print('')
print('shape:', x.shape)

[[57 67]
 [99 43]]

shape: (2, 2)


In [14]:
y = np.array([[75,21],[57,12]])
print(y)
print('')
print('shape:', y.shape)

[[75 21]
 [57 12]]

shape: (2, 2)


In [15]:
z = np.array([[87,26],[18,84]])
print(z)
print('')
print('shape:', z.shape)

[[87 26]
 [18 84]]

shape: (2, 2)


In [16]:
ListOfMatrix = [w,x,y,z]
tensor = np.array(ListOfMatrix)
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [17]:
tensor.shape

(4, 2, 2)

# 2. Lakukan perkalian terhadap matrix 

In [26]:

𝐴=np.array([[23,50,19],
           [7,12,109],
           [57,67,98]]) 
𝐵=np.array([17,
            22,
            19])


In [24]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [27]:
B

array([17, 22, 19])

In [28]:
A@B

array([1852, 2454, 4305])

# 3. Lakukan Transpose, hitung determinan, dan inverse 


In [30]:
𝐴=np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [31]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])