# Non Graded Challenge 5

 `Name               : Reyki Seprianza`
 `Batch              : FTDS009`

----------------------------------

Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Linear Algebra.

---------------------------------


## Assignment Instructions
Apakah 

$\begin{bmatrix}1 \3\end{bmatrix}$ 

adalah eigenvector dari 

$\begin{bmatrix}1 & -1\6 &-4 \end{bmatrix}$

? Jika iya, berapakah eigenvalue-nya?

## Assignment Submission
Simpan assignment pada sesi ini dengan nama h8dsft_Linear_Algebra3.
Push Assigment yang telah kalian buat ke akun Github kalian masing-masing.
## Assignment Objectives
Non-Graded Assignment ini dibuat guna mengevaluasi konsep Linear Algebra sebagai berikut:

- Memahami konsep eigenvalue dan eigenvector
- Dapat mencari eigenvalue dan eigenvector



https://github.com/ardhiraka/FSDS_Guidelines/blob/master/p0/w2/assignments/NG6.md

https://www.kode.id/courses/take/ftds0/pdfs/26440113-non-graded-challenge-5

In [14]:
import numpy as np
from numpy.linalg import eig 

In [3]:
a= np.array([[1],[3]])
a

array([[1],
       [3]])

In [4]:
b= np.array([[1, -1],
            [6,4]])
b

array([[ 1, -1],
       [ 6,  4]])

In [6]:
from numpy.linalg import eig
eigval, eigvec = eig(b)

In [7]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [8]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [12]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [15]:
A = np.array ([1,3])
B = np.array ([[1,-1],[6,4]])

def plot_vector2d(vector2d, origin=[0, 0]):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              )
plot_vector2d(A, c="r")
plot_vector2d(v, c="b")
plt.axis([0, 19, 0, 19])
plt.grid()

v = A @ B
v

TypeError: plot_vector2d() got an unexpected keyword argument 'c'