In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

> Now Import Plotly libraries

In [3]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.offline import download_plotlyjs, init_notebook_mode,plot
init_notebook_mode(connected=True)
import cufflinks as cf
cf.go_offline()

# Read Data

In [4]:
df = pd.read_csv('deployment/supermarket_sales.csv')
df.head()

Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   
3  123-19-1176      A     Yangon        Member    Male   
4  373-73-7910      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle       46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty       58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel       86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross margin percentage  gross income  Rating  
0  13:08      Ewallet  522.83                 4.761905       26.1415     9.1  
1  10:29         Cash   76.40                 4.761905        3.8200     9.6  
2  13:23  Credit card  324.31                 4.761905       16.2155     7.4  
3  20:33      Ewallet  465.76                 4.761905       23.2880     8.4  
4  10:37      Ewallet  604.17                 4.761905       30.2085     5.3

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               1000 non-null   object 
 1   Branch                   1000 non-null   object 
 2   City                     1000 non-null   object 
 3   Customer type            1000 non-null   object 
 4   Gender                   1000 non-null   object 
 5   Product line             1000 non-null   object 
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64  
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object 
 11  Time                     1000 non-null   object 
 12  Payment                  1000 non-null   object 
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  

In [6]:
df.describe()

Unit price     Quantity       Tax 5%        Total        cogs  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000   
mean     55.672130     5.510000    15.379369   322.966749   307.58738   
std      26.494628     2.923431    11.708825   245.885335   234.17651   
min      10.080000     1.000000     0.508500    10.678500    10.17000   
25%      32.875000     3.000000     5.924875   124.422375   118.49750   
50%      55.230000     5.000000    12.088000   253.848000   241.76000   
75%      77.935000     8.000000    22.445250   471.350250   448.90500   
max      99.960000    10.000000    49.650000  1042.650000   993.00000   

       gross margin percentage  gross income      Rating  
count             1.000000e+03   1000.000000  1000.00000  
mean              4.761905e+00     15.379369     6.97270  
std               6.131498e-14     11.708825     1.71858  
min               4.761905e+00      0.508500     4.00000  
25%               4.761905e+00      5.924875     5.50000  
50%               4.761905e+00     12.088000     7.00000  
75%               4.761905e+00     22.445250     8.50000  
max               4.761905e+00     49.650000    10.00000

# Exploratory Data Analysis

> Now create advance level plots using Plotly

In [7]:
fig = px.histogram(df,x= 'Customer type',color='Gender',barmode='group',
                   title='Total Count of Customer type')
fig

In [8]:
fig = px.histogram(df,x= 'Branch',color='Gender',barmode='group',
                   title='Total count of Branches')
fig

In [9]:
fig = px.histogram(df,x= 'Payment',barmode='group',
                   title='Count of Payment types ')
fig

In [10]:
fig = px.histogram(df,x= 'Payment',barmode='group',color='Gender',
                   title='Count of Payment types ')
fig

In [11]:
fig = px.bar(df,x='Product line',y='Unit price',title='Unit prices of Product')
fig.update_layout(uniformtext_minsize=8 , xaxis_tickangle=-45)

In [12]:
fig = px.bar(df,x='Product line',y='Unit price',color='Gender',barmode='group',title='Unit prices of product per Gender count')
fig.update_layout(uniformtext_minsize=8 , xaxis_tickangle=-45)

In [13]:
px.bar(df,x='City',y='Rating',title='Rating of Items per City')

In [14]:
px.bar(df,x='Customer type',y='Rating',color='Gender',barmode='group',title='Customer type Rating')

In [15]:
px.bar(df,x='City',y='Total',color='City',animation_frame='Date',title='Change in the Total price of Country according to DATE',
      animation_group="Branch", range_y=[0,1000])

Here we note that at 3/22/2019, there is no sale in City Naypyi

In [16]:
df.head(2)

Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   

             Product line  Unit price  Quantity   Tax 5%     Total      Date  \
0       Health and beauty       74.69         7  26.1415  548.9715  1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200  3/8/2019   

    Time  Payment    cogs  gross margin percentage  gross income  Rating  
0  13:08  Ewallet  522.83                 4.761905       26.1415     9.1  
1  10:29     Cash   76.40                 4.761905        3.8200     9.6

# Data Cleaning

In [17]:
df.drop(['Invoice ID','Branch','Tax 5%','Date','Time','gross margin percentage','gross income'],
       axis=1,inplace=True)

In [18]:
df.head()

City Customer type  Gender            Product line  Unit price  \
0     Yangon        Member  Female       Health and beauty       74.69   
1  Naypyitaw        Normal  Female  Electronic accessories       15.28   
2     Yangon        Normal    Male      Home and lifestyle       46.33   
3     Yangon        Member    Male       Health and beauty       58.22   
4     Yangon        Normal    Male       Sports and travel       86.31   

   Quantity     Total      Payment    cogs  Rating  
0         7  548.9715      Ewallet  522.83     9.1  
1         5   80.2200         Cash   76.40     9.6  
2         7  340.5255  Credit card  324.31     7.4  
3         8  489.0480      Ewallet  465.76     8.4  
4         7  634.3785      Ewallet  604.17     5.3

> will get the dummy variable format for the data

In [19]:
df_dummies = pd.get_dummies(df)

In [20]:
df_dummies.head()

Unit price  Quantity     Total    cogs  Rating  City_Mandalay  \
0       74.69         7  548.9715  522.83     9.1              0   
1       15.28         5   80.2200   76.40     9.6              0   
2       46.33         7  340.5255  324.31     7.4              0   
3       58.22         8  489.0480  465.76     8.4              0   
4       86.31         7  634.3785  604.17     5.3              0   

   City_Naypyitaw  City_Yangon  Customer type_Member  Customer type_Normal  \
0               0            1                     1                     0   
1               1            0                     0                     1   
2               0            1                     0                     1   
3               0            1                     1                     0   
4               0            1                     0                     1   

   ...  Gender_Male  Product line_Electronic accessories  \
0  ...            0                                    0   
1  ...            0                                    1   
2  ...            1                                    0   
3  ...            1                                    0   
4  ...            1                                    0   

   Product line_Fashion accessories  Product line_Food and beverages  \
0                                 0                                0   
1                                 0                                0   
2                                 0                                0   
3                                 0                                0   
4                                 0                                0   

   Product line_Health and beauty  Product line_Home and lifestyle  \
0                               1                                0   
1                               0                                0   
2                               0                                1   
3                               1                                0   
4                               0                                0   

   Product line_Sports and travel  Payment_Cash  Payment_Credit card  \
0                               0             0                    0   
1                               0             1                    0   
2                               0             0                    1   
3                               0             0                    0   
4                               1             0                    0   

   Payment_Ewallet  
0                1  
1                0  
2                0  
3                1  
4                1  

[5 rows x 21 columns]

In [21]:
df_dummies = df_dummies.round(0)

# Model Training

> Now it's time to do a train test split, and train our model!

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X = df_dummies.drop('Rating',axis=1)
y = df_dummies['Rating']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
logmodel = LogisticRegression(max_iter=10000)

In [27]:
logmodel.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

# Predictions and Evaluations

>  Now predict values for the testing dat

In [28]:
predictions = logmodel.predict(X_test)

In [29]:
from sklearn.metrics import classification_report,confusion_matrix

In [30]:
print(confusion_matrix(y_test,predictions))

[[ 1  5 16  7 11  0  0]
 [ 2  2 20  5 10  1  0]
 [ 1  5 26  9 20  2  0]
 [ 1  6 25 10  8  2  0]
 [ 1 11 22 13 13  1  0]
 [ 0  3 25  7 14  2  0]
 [ 0  2 11  4  6  0  0]]


In [31]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         4.0       0.17      0.03      0.04        40
         5.0       0.06      0.05      0.05        40
         6.0       0.18      0.41      0.25        63
         7.0       0.18      0.19      0.19        52
         8.0       0.16      0.21      0.18        61
         9.0       0.25      0.04      0.07        51
        10.0       0.00      0.00      0.00        23

    accuracy                           0.16       330
   macro avg       0.14      0.13      0.11       330
weighted avg       0.16      0.16      0.13       330



C:\Users\acer\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [32]:
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

MAE: 1.7272727272727273
MSE: 4.4363636363636365
RMSE: 2.106267702919939


> Great