belajar series dan data frame, seperti mengakses element di list, dan mencoba mengkombinasikan data sheet atau lebih dari 1 tabel di kombinasikan, dan akan belajhar mising values untuk mengisi hal yg hilang


pandas merupakan library yg high performe mobility,

data sheet kita umumnya berbentuk tabel, ini adalah library yang paling sering di gunakan karena bersifart tabel, karena ga selalu bersih data sheet nya
banyak yg butruh kita replace, kita butuh pandas 

ada  struktur data
## data series dan data frame

frame = bentuknya tabel, atau kumpulan kolom
series = salah satu kolom saja (bentuk paling sederhana)

kumpulan seris adalah data frame

seris merupakan 1 dimensional tabel array, setidaknya ada 2 komponen
1.value
2.index atau identyfier

dataframe punya 3 komponen
1.values
2.kolom
3.indeks

In [92]:
import pandas as pd
import numpy as np

untuk membuat series

In [93]:
pd.Series([4.5,3.0,2.1])

0    4.5
1    3.0
2    2.1
dtype: float64

In [94]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [95]:
pd.Series(['a','b','c',4.5,3.0,2.1])

0      a
1      b
2      c
3    4.5
4      3
5    2.1
dtype: object

tipe data OBJEK memakan memori lebih besar dari yg lainnya

In [96]:
revenues = pd.Series([5555,7000,1980])
revenues

0    5555
1    7000
2    1980
dtype: int64

In [97]:
revenues.values

array([5555, 7000, 1980], dtype=int64)

In [98]:
revenues.index

RangeIndex(start=0, stop=3, step=1)

In [99]:
city_revenues = pd.Series(
    [4200,800,6500],
    index=['Amsterdam','Toronto','Tokyo']
)
city_revenues

Amsterdam    4200
Toronto       800
Tokyo        6500
dtype: int64

di atas jadi seolah ada idex, kedepan kita bisa menggunakan dictanory
tipe data berpasangan antara keys dan value
## {keys:value}
    nama index : value

In [100]:
city_employe_count = pd.Series({'amsterdam':5,'tokyo':8, })
city_employe_count

amsterdam    5
tokyo        8
dtype: int64

In [101]:
city_employe_count.keys() #memanggil semua keys

Index(['amsterdam', 'tokyo'], dtype='object')

In [102]:
'tokyo' in city_employe_count #melihat ada ga tokyo di keys dictory

True

In [103]:
'palembang' in city_employe_count #lihat data boleannya

False

In [104]:
8 in city_employe_count # false karena dia ga cek values tapi cuma index

False

In [105]:
10 in city_employe_count

False

In [106]:
city_employe_count.values

array([5, 8], dtype=int64)

sekarang kita coba ke pandas

In [107]:
# pd.DataFrame({
#     'nama kolom 1': value kolom 1,
#     'nama kolom 2' : value kolom 2
# })

In [108]:
city_revenues

Amsterdam    4200
Toronto       800
Tokyo        6500
dtype: int64

In [109]:
city_employe_count

amsterdam    5
tokyo        8
dtype: int64

In [110]:
city_data = pd.DataFrame({
    'revenue': city_revenues,
    'employee_count':city_employe_count
})
city_data

#NaN adalah missing values yang harus di benerin nantiny

revenue  employee_count
Amsterdam   4200.0             NaN
Tokyo       6500.0             NaN
Toronto      800.0             NaN
amsterdam      NaN             5.0
tokyo          NaN             8.0

data frame kan punya 3 komponen
kolom, index, value

In [111]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto', 'amsterdam', 'tokyo'], dtype='object')

In [112]:
city_data.values

array([[4.2e+03,     nan],
       [6.5e+03,     nan],
       [8.0e+02,     nan],
       [    nan, 5.0e+00],
       [    nan, 8.0e+00]])

cara baca di atas
4.2 x 10 pangkat 3 = 4200

In [113]:
city_data.axes

[Index(['Amsterdam', 'Tokyo', 'Toronto', 'amsterdam', 'tokyo'], dtype='object'),
 Index(['revenue', 'employee_count'], dtype='object')]

city_data.axes[0] #harus di hapalin perubahan ini di baris atau kolom
# axis 0 = baris
city_data.axes[1]
# axis 1 =kolom

nanti akan berguna jika kita mau drop missing values

In [114]:
city_data.axes[0] #harus di hapalin perubahan ini di baris atau kolom
#axis 0 = baris

Index(['Amsterdam', 'Tokyo', 'Toronto', 'amsterdam', 'tokyo'], dtype='object')

In [115]:
city_data.axes[1]
#axis 1 =kolom

Index(['revenue', 'employee_count'], dtype='object')

In [116]:
city_data.columns

Index(['revenue', 'employee_count'], dtype='object')

kita coba akses series pake.loc atau .iloc

In [117]:
city_revenues
#ada label dan values
# di belakang layar tetap indeks nya ada mulai dari 0 ya

Amsterdam    4200
Toronto       800
Tokyo        6500
dtype: int64

In [118]:
city_revenues['toronto']

KeyError: 'toronto'

In [ ]:
city_revenues[1]

800

In [ ]:
city_revenues[-1]

6500

In [ ]:
city_revenues[:1]

amsterdam    4200
dtype: int64

In [ ]:
city_revenues[1:]

toronto     800
tokyo      6500
dtype: int64

.loc = akses berdasarkan label ini isinya
.iloc = kita akses berdasarkan indexx 0,1,2,3,4 dst

In [ ]:
colors = pd.Series(
    ["red", "purple", "blue", "green", "yellow"],
    index=[1, 2, 3, 5, 8]
)
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [ ]:
colors[1]

'red'

In [ ]:
colors[0] # ini eror karena tak di definisikan

KeyError: 0

In [ ]:
colors.loc[1] # manggil label

'red'

In [ ]:
colors.iloc[1] # manggil index

'purple'

In [ ]:
colors.iloc[1:3] #index

2    purple
3      blue
dtype: object

In [ ]:
colors.loc[1:3] #label

1       red
2    purple
3      blue
dtype: object

In [ ]:
colors.iloc[0:4:2]

1     red
3    blue
dtype: object

In [ ]:
colors.iloc[[0,2]]

1     red
3    blue
dtype: object

In [ ]:
colors


1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [ ]:
colors.loc[3:8]

3      blue
5     green
8    yellow
dtype: object

In [ ]:
colors[[1,3,8]]

1       red
3      blue
8    yellow
dtype: object

In [ ]:
colors.loc[1:8:2]

1       red
3      blue
8    yellow
dtype: object

In [ ]:
city_data.loc['amsterdam':]

revenue  employee_count
amsterdam     4200             5.0
tokyo         6500             8.0
toronto        800             NaN

In [ ]:
city_data.loc['tokyo']

revenue           6500.0
employee_count       8.0
Name: tokyo, dtype: float64

In [ ]:
city_data
#ada 2 kolom ne

revenue  employee_count
amsterdam     4200             5.0
tokyo         6500             8.0
toronto        800             NaN

In [ ]:
city_data['revenue'] #isi kolom revenue

amsterdam    4200
tokyo        6500
toronto       800
Name: revenue, dtype: int64

In [ ]:
city_data.revenue #cara ini bisa aja miss

amsterdam    4200
tokyo        6500
toronto       800
Name: revenue, dtype: int64

kalo panggil pake . ada kekurangan, kalo misal ada kesamaan nama di metod atau data frame nanti dia bingung mau pangiiil siapa

kalo kita mau panggil lebih dari 1 kolom gimana tingga ltambh aja kasi koma trs panggiill

In [ ]:
city_data

revenue  employee_count
amsterdam     4200             5.0
tokyo         6500             8.0
toronto        800             NaN

In [ ]:
city_data.loc['amsterdam']

revenue           4200.0
employee_count       5.0
Name: amsterdam, dtype: float64

In [ ]:
city_data.loc['amsterdam': 'tokyo']

revenue  employee_count
amsterdam     4200             5.0
tokyo         6500             8.0

In [ ]:
city_data.loc['tokyo',:]

revenue           6500.0
employee_count       8.0
Name: tokyo, dtype: float64

In [ ]:
city_data.loc['amsterdam':'tokyo','revenue']
#panggil label apa aja di awal, terus panggil kolom spesifik yg mna 

amsterdam    4200
tokyo        6500
Name: revenue, dtype: int64

In [ ]:
city_revenues

amsterdam    4200
toronto       800
tokyo        6500
dtype: int64

In [ ]:
city_revenues.sum

<bound method Series.sum of amsterdam    4200
toronto       800
tokyo        6500
dtype: int64>

In [ ]:
city_revenues.sum()

11500

In [ ]:
city_revenues.max()

6500

In [ ]:
city_revenues.mean()

3833.3333333333335

combining multiple data set

## bisa make motede concate dan merge

In [ ]:
further_city_data = pd.DataFrame(
    {"revenue": [7000, 3400], "employee_count": [2, 2]},
    index=["New York", "Barcelona"]
)

In [ ]:
further_city_data

revenue  employee_count
New York      7000               2
Barcelona     3400               2

In [ ]:
city_data


revenue  employee_count
amsterdam     4200             5.0
tokyo         6500             8.0
toronto        800             NaN

ni data mau kita gabungin kita coba memanjang kebawah setelah itu ke samping

In [119]:
all_city_data = pd.concat([city_data,further_city_data], sort=False)
all_city_data

revenue  employee_count
Amsterdam   4200.0             NaN
Tokyo       6500.0             NaN
Toronto      800.0             NaN
amsterdam      NaN             5.0
tokyo          NaN             8.0
New York    7000.0             2.0
Barcelona   3400.0             2.0

In [121]:
city_countries = pd.DataFrame({
    "country": ["Holland", "Japan", "Holland", "Canada", "Spain"],
    "capital": [1, 1, 0, 0, 0]},
    index=["Amsterdam", "Tokyo", "Rotterdam", "Toronto", "Barcelona"]
)
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0

kita akan menggabungkan datanya secara menyamping

In [122]:
all_city_data


revenue  employee_count
Amsterdam   4200.0             NaN
Tokyo       6500.0             NaN
Toronto      800.0             NaN
amsterdam      NaN             5.0
tokyo          NaN             8.0
New York    7000.0             2.0
Barcelona   3400.0             2.0

In [124]:
cities = pd.concat([all_city_data, city_countries], axis=1, sort=False) #bedaya ini ada axis
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             NaN  Holland      1.0
Tokyo       6500.0             NaN    Japan      1.0
Toronto      800.0             NaN   Canada      0.0
amsterdam      NaN             5.0      NaN      NaN
tokyo          NaN             8.0      NaN      NaN
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

yg bikin dia ke samping itu gr" ada axis=1 ya, klo axis=0
default nya axis = 0

di atas ga berurutan karena sort = False kalo True urutan tapi lebih lebih lama

In [125]:
cities = pd.concat([all_city_data, city_countries], axis=1, sort=True) #bedaya ini ada axis
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             NaN  Holland      1.0
Barcelona   3400.0             2.0    Spain      0.0
New York    7000.0             2.0      NaN      NaN
Rotterdam      NaN             NaN  Holland      0.0
Tokyo       6500.0             NaN    Japan      1.0
Toronto      800.0             NaN   Canada      0.0
amsterdam      NaN             5.0      NaN      NaN
tokyo          NaN             8.0      NaN      NaN

parameter concat ada juga yang outer dan inner join

## inner join kita hanya menggambil data yang ada kesamaan kalo outer ambil semua

In [126]:
all_city_data

revenue  employee_count
Amsterdam   4200.0             NaN
Tokyo       6500.0             NaN
Toronto      800.0             NaN
amsterdam      NaN             5.0
tokyo          NaN             8.0
New York    7000.0             2.0
Barcelona   3400.0             2.0

In [127]:
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0

kalo kita iiner dia akan menggabungkan yang bersinggungan saja jadio yg gada ga di masuykin seperti yang amsterdam typo atau si newyork yg gada disana

In [128]:
pd.concat([all_city_data,city_countries], axis=1, join='inner')

revenue  employee_count  country  capital
Amsterdam   4200.0             NaN  Holland        1
Tokyo       6500.0             NaN    Japan        1
Toronto      800.0             NaN   Canada        0
Barcelona   3400.0             2.0    Spain        0

sekarang kita coba make merge

In [129]:
countries = pd.DataFrame({
    "population_millions": [17, 127, 37],
    "continent": ["Europe", "Asia", "North America"]
}, index=["Holland", "Japan", "Canada"])
countries

population_millions      continent
Holland                   17         Europe
Japan                    127           Asia
Canada                    37  North America

penggabungan 2 tabel jadi kita bisa atur siapa yg di kiri yaitu yg pertama di sebut

In [130]:
pd.merge(cities, countries, left_on="country", right_index=True)

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             NaN  Holland      1.0                   17   
Rotterdam      NaN             NaN  Holland      0.0                   17   
Tokyo       6500.0             NaN    Japan      1.0                  127   
Toronto      800.0             NaN   Canada      0.0                   37   

               continent  
Amsterdam         Europe  
Rotterdam         Europe  
Tokyo               Asia  
Toronto    North America

In [131]:
pd.merge(
    cities,
    countries,
    left_on="country",
    right_index=True,
    how="left"
)

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             NaN  Holland      1.0                 17.0   
Barcelona   3400.0             2.0    Spain      0.0                  NaN   
New York    7000.0             2.0      NaN      NaN                  NaN   
Rotterdam      NaN             NaN  Holland      0.0                 17.0   
Tokyo       6500.0             NaN    Japan      1.0                127.0   
Toronto      800.0             NaN   Canada      0.0                 37.0   
amsterdam      NaN             5.0      NaN      NaN                  NaN   
tokyo          NaN             8.0      NaN      NaN                  NaN   

               continent  
Amsterdam         Europe  
Barcelona            NaN  
New York             NaN  
Rotterdam         Europe  
Tokyo               Asia  
Toronto    North America  
amsterdam            NaN  
tokyo                NaN

metode mergge hanya bisa ke samping ga bisa ke bawah

In [132]:
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             NaN  Holland      1.0
Barcelona   3400.0             2.0    Spain      0.0
New York    7000.0             2.0      NaN      NaN
Rotterdam      NaN             NaN  Holland      0.0
Tokyo       6500.0             NaN    Japan      1.0
Toronto      800.0             NaN   Canada      0.0
amsterdam      NaN             5.0      NaN      NaN
tokyo          NaN             8.0      NaN      NaN

# review yang di pelajarin



Pandas Basic, 
Series dan DataFrame
series ada value dan index
dataframe datafalue, value, kolom

kita bisa memanfaaatkan LOC dan ILOC untuk manggil atau akses
untuk mencari jg bisa spesifik tadi di []

terus belajar tentang gabungin data
pake concat
axis 0 dia ke bawah
axis 1 dia k samping

bisa juga di merge
di merge banyak lagi HOW nya
tapi hanya bisa ke samping saja


concat refrensinya index aja
kalo merge bisa menggunakan refrensi dari kolom

## masih harus belajar lagi buat yg di bahas terutama di merge ini

# INI SESI SIANG

KITA AMBIL DATA DARI KAGGLE