In [1]:
!pip install numpy

## numpy 
suatu pacage yg di gunakan untuk kalkulasi
untuk bikin matriks dan kalkulasi

In [9]:
import numpy as np


In [11]:
a = np.array ([1,2,4])
a

array([1, 2, 4])

In [12]:
tinggi= [1.7,1.8,2.0]
berat =[78.8,56.2,97.4]

In [14]:
np.zeros(6)
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.empty(4)

array([1.37172523e-311, 1.33511562e-306, 6.23040373e-307, 1.60219035e-306])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
print(np.arange(4,10,2))

[4 6 8]


In [18]:
arr = np.array ([1,2,3,4])
np.append(arr,[1,2,3])

array([1, 2, 3, 4, 1, 2, 3])

In [20]:
np.delete(arr, 1)

array([1, 3, 4])

In [21]:
arr

array([1, 2, 3, 4])

In [22]:
np.sort(arr)

array([1, 2, 3, 4])

In [37]:
array_example = np.array ([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

0-D
1-D vektor
2-D metriks
3-d

In [23]:
arr = np.array ([4,2,3])
print (arr)
#1d

[4 2 3]


In [24]:
arr = np.array (9)
print (arr)
#0d

9


In [26]:
arr = np.array ([[4,2,3], [2,6,8]])
print (arr)
#2d

[[4 2 3]
 [2 6 8]]


In [33]:
arr = np.array ([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print (arr)
#3d
# masih salah

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
array_example.ndim


3

In [39]:
array_example.shape

(2, 2, 2)

In [40]:
array_example.size


8

In [54]:
a= np.arange(10)
print(a)

[0 1 2 3]


In [59]:
matriks= a.reshape(2,2)
print(matriks)

[[0 1]
 [2 3]]


In [60]:
a = np.array ([1,2,3,4,5,6])
a.shape

(6,)

In [61]:
a2 = a[np.newaxis]
print (a2.shape)
print (a2)

(1, 6)
[[1 2 3 4 5 6]]


In [62]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [63]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [64]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [65]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [70]:
arr= np.array([2,3,7,8,9])
print(arr[2:5])
print(arr[2:5:3])
print(arr[ : : 2])
print(arr[:3:2])

[7 8 9]
[7]
[2 7 9]
[2 7]


In [87]:
arr= np.array([[2,3,7,8,9],[1,3,6,8,7]])
print(arr[1, 1:3])
print(arr[1, 1:4])
print(arr[0, 1:4])
print(arr[2:4,2])
print(arr[0:2,2])
# yg kiri ambil urutan secara besar, di kanan ambil urutan di dalam
\

print(arr[1:4]) #panggil aray index pertama aja
print('pusing ga lu '*10)
print(arr[0:3]) 

print(arr[:-1])

[3 6]
[3 6 8]
[3 7 8]
[]
[7 6]
[[1 3 6 8 7]]
pusing ga lu pusing ga lu pusing ga lu pusing ga lu pusing ga lu pusing ga lu pusing ga lu pusing ga lu pusing ga lu pusing ga lu 
[[2 3 7 8 9]
 [1 3 6 8 7]]
[[2 3 7 8 9]]


In [92]:
arr= np.array([[2,3,7,8,9],[1,3,6,8,7],[1,3,6,8,7]])
print (arr[1:3,2:4])

[[6 8]
 [6 8]]


In [94]:
a= np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
a_1= np.array ([[2,3],
                [4,2]])
a_2= np.array ([[5,7],
                [6,5]])

In [98]:
np.vstack((a_1,a_2))

array([[2, 3],
       [4, 2],
       [5, 7],
       [6, 5]])

In [99]:
np.hstack((a_1,a_2))

array([[2, 3, 5, 7],
       [4, 2, 6, 5]])

In [100]:
data_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [102]:
new_arr= data_1.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [104]:
new_arr= data_1.reshape(2,2,-1) #-1 adalah unown misal kita gatau jadi dimensinya akan sesuai dengan element yg ada
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [105]:
new_arr.shape

(2, 2, 3)

In [111]:
def convert(fahr):
    cels = fahr * 1.8 + 32.0
    return cels 
print(convert(32))


89.6


In [117]:
def convert(fahr,kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv -273.15
    return cels    
print("Temperature in celcius ( C ) = ", convert(32,20))


Temperature in celcius ( C ) =  (89.6, -253.14999999999998)


In [119]:
def convert(fahr,kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv -273,15
    return cels, cels2    
print("Temperature in celcius ( C ) = ", convert(32,20))


Temperature in celcius ( C ) =  (89.6, (-253, 15))


In [120]:
def temp_converter(ftemp):
     ctemp = (ftemp - 32) * (5/9)
     ktemp = ctemp + 273.15
     return [ftemp, ktemp, ctemp]

print(temp_converter(72))


[72, 295.3722222222222, 22.22222222222222]


In [121]:
def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total
print(sum((8, 2, 3, 0, 7)))


20


In [127]:
def my_function():
    st ='jojo'
    y = 35
    return st,y

In [130]:
a = my_function()
print(a[0])

jojo


In [132]:
a,b = my_function()
print(a)
print(b)

jojo
35


In [133]:
(my_function()[0])

'jojo'