# **Matrix**

In [ ]:
import numpy as np

In [ ]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [ ]:
vector.shape

(3,)

In [ ]:
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
matrix.shape

(3, 2)

## **akses elemen matrix**

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][2]

6

In [ ]:
A[1, 2]

6

In [ ]:
A[:, -1]

array([3, 6, 9])

In [ ]:
np.diag(A)

array([1, 5, 9])

In [ ]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## **Operasi Aritmatika**
- penjumlahan
- pengurangan
- pembagian
- perkalian

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B = np.array([[1, 8, 2],
              [2, 1, 1],
              [4, 0, 1]])
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

**penjumlahan**

In [ ]:
# matrix dengan matrix
A + B

array([[ 2, 10,  5],
       [ 6,  6,  7],
       [11,  8, 10]])

**pengurangan**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [ ]:
A - B

array([[ 0, -6,  1],
       [ 2,  4,  5],
       [ 3,  8,  8]])

**pembagian**

In [ ]:
B / A

array([[1.        , 4.        , 0.66666667],
       [0.5       , 0.2       , 0.16666667],
       [0.57142857, 0.        , 0.11111111]])

**perkalian**
- matrix-scalar
- hadamard product (element wise)
- matrix-matrix (@)

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [ ]:
# matrix-scalar
10 * A

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# hadamard product (element wise)
A * B

array([[ 1, 16,  6],
       [ 8,  5,  6],
       [28,  0,  9]])

In [ ]:
# matrix-matrix multiplication (@)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [ ]:
A @ B

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [ ]:
np.dot(A, B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [ ]:
A.dot(B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
C = np.array([[2],
              [1],
              [5]])

C

array([[2],
       [1],
       [5]])

In [ ]:
C.shape

(3, 1)

In [ ]:
F = A @ C
F

array([[19],
       [43],
       [67]])

In [ ]:
F.shape

(3, 1)

**Transpose**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Invers**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [ ]:
D = np.array([[1, 2],
              [3, 4]])

D_adj = np.array([[4, -2],
                  [-3, 1]])

In [ ]:
inv_D = 1/np.linalg.det(D) * D_adj
inv_D

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(D)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(B)

array([[ 0.11111111, -0.88888889,  0.66666667],
       [ 0.22222222, -0.77777778,  0.33333333],
       [-0.44444444,  3.55555556, -1.66666667]])

In [ ]:
np.linalg.inv(A)

LinAlgError: ignored

**Determinant**

In [ ]:
np.linalg.det(A)

0.0

In [ ]:
E = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 0, 1]])

E

array([[1, 2, 3],
       [2, 4, 6],
       [1, 0, 1]])

In [ ]:
np.linalg.det(E)

0.0

In [ ]:
np.linalg.inv(E) # beberapa matriks tidak memiliki invers, matriks dengan det = 0

LinAlgError: ignored

In [ ]:
0.1 + 0.2

0.30000000000000004

**Tensor**

In [ ]:
X = np.array([[1, 4, 5, 6],
              [4, 3, 7, 1]])

print(X)
print('')
print('shape: ', X.shape)

[[1 4 5 6]
 [4 3 7 1]]

shape:  (2, 4)


In [ ]:
Y = np.array([[2, 8, 8, 1],
              [3, 0, 9, 1]])

print(Y)
print('')
print('shape: ', Y.shape)

[[2 8 8 1]
 [3 0 9 1]]

shape:  (2, 4)


In [ ]:
Z = np.array([[2, 4, 1, 1],
              [0, 9, 4, 2]])

print(Z)
print('')
print('shape: ', Z.shape)

[[2 4 1 1]
 [0 9 4 2]]

shape:  (2, 4)


In [ ]:
list_of_matrix = [X, Y, Z]
tensor = np.array(list_of_matrix)
tensor

array([[[1, 4, 5, 6],
        [4, 3, 7, 1]],

       [[2, 8, 8, 1],
        [3, 0, 9, 1]],

       [[2, 4, 1, 1],
        [0, 9, 4, 2]]])

In [ ]:
tensor.shape

(3, 2, 4)